### ISSUE TITLE
Error during processing of: observationAssertions.ts

### ISSUE THREAD

**Issue by shalini-haribabu** [mbolotov/intellij-cypress#58]
Error during processing of: observationAssertions.ts

com.intellij.diagnostic.PluginException: Cannot load class me.mbolotov.cypress.lang.AliasReferenceResolve (
  error: com/intellij/model/SymbolReference,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Cypress Support Pro, id=me.mbolotov.cypress.pro, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2021.2/plugins/Cypress Support Pro, version=2.3.0, package=null), packagePrefix=null, instanceId=80, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:441)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:275)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:251)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at me.mbolotov.cypress.lang.AliasReferenceMixin.getReference(Unknown Source)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.getReferences(SharedPsiElementImplUtil.java:76)
	at com.intellij.psi.impl.PsiElementBase.getReferences(PsiElementBase.java:81)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:39)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:26)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:952)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:88)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:179)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:205)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:132)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processInjectedFile(LowLevelSearchUtil.java:54)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:83)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:179)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:205)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:948)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:273)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:264)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$17(PsiSearchHelperImpl.java:909)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$10(PsiSearchHelperImpl.java:545)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:524)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:393)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:466)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:465)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:138)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:152)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:45)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesConcurrentlyDespiteWriteActions(PsiSearchHelperImpl.java:482)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processPsiFileRoots(PsiSearchHelperImpl.java:390)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processCandidates(PsiSearchHelperImpl.java:904)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequests(PsiSearchHelperImpl.java:874)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequestsOptimized(PsiSearchHelperImpl.java:840)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:765)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$createUsageSearcher$10(FindUsagesManager.java:423)
	at com.intellij.find.findUsages.FindUsagesManager$1.run(FindUsagesManager.java:320)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: com/intellij/model/SymbolReference
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:290)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:217)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:176)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:433)
	... 70 more
Caused by: java.lang.ClassNotFoundException: com.intellij.model.SymbolReference PluginClassLoader(plugin=PluginDescriptor(name=Cypress Support Pro, id=me.mbolotov.cypress.pro, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2021.2/plugins/Cypress Support Pro, version=2.3.0, package=null), packagePrefix=null, instanceId=80, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 78 more

**Comment by mbolotov** [comment]
Hello @shalini-haribabu!
Could you please open IDE settings and check the plugin version?
![image](https://user-images.githubusercontent.com/19785715/129156326-a784fe6c-37b1-4739-b5a4-256e4f6e8fdb.png)

It must be `2.3.0-2021.2` (ending with the '2021.2' suffix) to work with WebStorm 2021.2 version.

**Comment by shalini-haribabu** [comment]
Thanks Mikhail! It fixed the issue.


Shalini Haribabu 
Quality Assurance Engineer
Schrödinger Building, Heatley Road, Oxford Science Park, Oxford, OX4 4GE
+44 (0) 3300 581 845(Office)
***@***.***
www.sensynehealth.com
This email is confidential and is intended for the addressee only. If you are not the addressee, please delete the email and do not use it in any way.  Sensyne Health Plc and its associated companies do not accept or assume responsibility for any use of or reliance on this email by anyone, other than the intended addressee to the extent agreed in the relevant contract for the matter to which this email relates (if any).  Sensyne Health Plc is a public limited company registered in England under registered number 11425451, with its registered address at: Schrödinger Building, Heatley Road, Oxford Science Park, Oxford, OX4 4GE.  Sensyne Health Plc and its associated companies may monitor outgoing and incoming emails and other telecommunications on its email and telecommunications systems; by replying to this email you give your consent to such monitoring.
From: Mikhail Bolotov ***@***.***>
Date: Thursday, 12 August 2021 at 08:35
To: mbolotov/intellij-cypress ***@***.***>
Cc: Shalini Haribabu ***@***.***>, Mention ***@***.***>
Subject: Re: [mbolotov/intellij-cypress] Error during processing of: observationAssertions.ts (#58)
This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello @shalini-haribabu<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshalini-haribabu&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106952741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=weK7uoY7ktK1mjtsF8F%2FjC5wBujBepNM6Iw17ry8l0s%3D&reserved=0>!
Could you please open IDE settings and check the plugin version?
[image]<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F19785715%2F129156326-a784fe6c-37b1-4739-b5a4-256e4f6e8fdb.png&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106962697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wRx8IvTjUIIOSRS1Vfh3bXxZ%2FoKUEsIRAG%2BjzIbN3tE%3D&reserved=0>

It must be 2.3.0-2021.2 (ending with the '2021.2' suffix) to work with WebStorm 2021.2 version.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmbolotov%2Fintellij-cypress%2Fissues%2F58%23issuecomment-897415968&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106962697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GX2pndjthp3I7ZTfmt%2Bads%2FeLTeB%2FI%2FNNcIn%2B6OHciM%3D&reserved=0>, or unsubscribe<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATR6CEY7HKNX7POXXQPTGIDT4N2SZANCNFSM5B7S6TXA&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106962697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kKWrv54C1qhpPdnCEaQ7P2a7OUp8YKHkhDD5rO86hZA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106972650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BEQD1P2UDdYyD%2BKIdKK8fQqDO89fgcKZN4%2BwsmCzKRw%3D&reserved=0> or Android<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cshalini.haribabu%40sensynehealth.com%7C5243ff95d2cf489e609e08d95d63b682%7C5e6aa86279f24bf990ce4a38bb780ac1%7C0%7C0%7C637643505106972650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ak5tWh%2BckNeU1xXsCnozX4SwnCLigaSdBPGaF3EG2zg%3D&reserved=0>.
